using System;

// Il2CppInterop emits its own System.Runtime.CompilerServices.NullableAttribute and
// NullableContextAttribute into UnityEngine.CoreModule.dll. Because we reference that
// assembly, Roslyn binds to those declarations when it needs to emit nullable metadata
// for the state machines generated by our `async` lambdas - and they do not carry the
// constructors it expects, so every async lambda fails with:
//
//   error CS0656: Missing compiler required member
//                 'System.Runtime.CompilerServices.NullableAttribute..ctor'
//
// A declaration inside the compilation being built wins over one from a referenced
// assembly, so defining them here resolves it. CS0436 (type conflicts with imported
// type) is already suppressed in Directory.Build.props.
//
// Nothing references these directly; the compiler emits them into our own metadata.

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.All, AllowMultiple = false, Inherited = false)]
    internal sealed class NullableAttribute : Attribute
    {
        public readonly byte[] NullableFlags;

        public NullableAttribute(byte flag) { NullableFlags = new[] { flag }; }
        public NullableAttribute(byte[] flags) { NullableFlags = flags; }
    }

    [AttributeUsage(
        AttributeTargets.Class | AttributeTargets.Delegate | AttributeTargets.Interface |
        AttributeTargets.Method | AttributeTargets.Module | AttributeTargets.Struct,
        AllowMultiple = false, Inherited = false)]
    internal sealed class NullableContextAttribute : Attribute
    {
        public readonly byte Flag;

        public NullableContextAttribute(byte flag) { Flag = flag; }
    }
}
